version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: products_api
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 3004:3000
    environment:
      DATABASE_URL: postgresql://postgres:randompassword@postgres-db:5432/products_api?schema=public
      PORT: 3000
volumes:
  postgres-db: {}
